apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      component: worker
  replicas: 3
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: kishoreiiitn/multi-worker
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: REDIS_HOST
              value: redis-clusterip-service
            - name: REDIS_PORT
              value: "6379"
